### ISSUE TITLE
Adding Types to pixi-cull

### ISSUE THREAD

**Issue by AdrienLemaire** [davidfig/pixi-cull#13]
> [tsserver 7016] [E] Could not find a declaration file for module 'pixi-cull'. `/path/to/project/node_modules/pixi-cull/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/pixi-cull` if it exists or add a new declaration (.d.ts) file containing `declare module 'pixi-cull';`

DefinitelyTypes doesn't have have type file for pixi-cull. But it'd be better to have the types directly in this repo. Like pixi-viewport does.

Thanks a lot for making this. Very useful <3

**Comment by davidfig** [comment]
I usually don't code in typescript. If you're willing to submit a PR or send me the types file, I can add it.
