### ISSUE TITLE
Some Sprites could disappeared when init out of screen in the beginning

### ISSUE THREAD

**Issue by zhouccccc** [davidfig/pixi-cull#21]
As stated in the title, If I put some sprites out of the viewport screen in the beginning of rendering, these sprites could disappeared when wheel the viewport  for view them. But not all sprites disappear, it seems to be random

Case 1
![image](https://user-images.githubusercontent.com/25141787/115977469-26919d80-a5ab-11eb-9437-2b7bf78a0f04.png)

Case 2
![image](https://user-images.githubusercontent.com/25141787/115977479-432dd580-a5ab-11eb-8db1-73098079c7ba.png)

The complete map looks like this
![image](https://user-images.githubusercontent.com/25141787/115977489-5ccf1d00-a5ab-11eb-9f89-269430a6fa7b.png)

Even though update the cull to the latest version

### version
![image](https://user-images.githubusercontent.com/25141787/115977524-a15ab880-a5ab-11eb-9fe3-25ec3207031a.png)

The following is my code:
![image](https://user-images.githubusercontent.com/25141787/115977536-cd763980-a5ab-11eb-9677-b88802257c12.png)

**Comment by davidfig** [comment]
It's difficult to figure out what's going on. The sample code seems straightforward and similar to the demo in pixi-cull. Do you know what's different from the demo project?

**Comment by zhouccccc** [comment]
there are no lots of differences. I think the only difference between them is that the demo show all sprites in the beginning, but my case is not. that's weird! 
Also If I remove the cull function, it works well. now I'm debugging the cull source code in my project

**Comment by davidfig** [comment]
What version of pixi-cull? If it's an older version, you could try: `new Simple({ dirtyTest: false })` and see if that helps.

**Comment by zhouccccc** [comment]
So sorry I forgot it because we download the source code and use it as the local static js module before. But the latest version can also reproduce

**Comment by davidfig** [comment]
Hmm...try to call addList after you added your elements to the children (it shouldn't need this but worth a try).

**Comment by zhouccccc** [comment]
I didn't add all children to the viewport or cull at one time. The following is the rendering logic:
![image](https://user-images.githubusercontent.com/25141787/115979015-fac7e500-a5b5-11eb-8bcb-06467e544945.png)
So how ( or where )do I do this action `addList` ?

**Comment by davidfig** [comment]
Maybe something like this (I'm guessing this is for a one-time render; you wouldn't want to recreate your scene on every frame like this for perf reasons):

1. create and add all sprites to the viewport
2. create a new cull (or remove old elements from cull)
3. call addList to cull
4. cull
5. render

**Comment by zhouccccc** [comment]
Thanks for your tips, I have resolved this issue because  I found my weird operation on creating some specific sprites . But my doubt is why I removed this module and then it can also works well. I will keep researching.  (>‿◠)
